### ISSUE TITLE
dump core while running wtlay

### ISSUE THREAD

**Issue by chklopp** [ruanjue/smartdenovo#10]
Hi,

I assemble a 1Gb genome using 17x of canu corrected reads. smartdenovo crashes at the last step : wtlay.

gdb /usr/local/bioinfo/src/smartdenovo/smartdenovo/wtlay core.180804
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-60.el6_4.1)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/bioinfo/src/smartdenovo/smartdenovo/wtlay...(no debugging symbols found)...done.
[New Thread 180804]
Missing separate debuginfo for 
Try: yum --disablerepo='*' --enablerepo='*-debug*' install /usr/lib/debug/.build-id/f7/95efbe6950d1523c5748594c166cedd4254c33
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Core was generated by `/usr/local/bioinfo/src/smartdenovo/smartdenovo/wtlay -i All7.fa.gz -b All7.dmo.'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004166b0 in merge_bubble_core_best_overlap_strgraph ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.5.x86_64

What could cause the crash?
What could I test to go further?

Ch+

**Comment by ruanjue** [comment]
Hi, thanks for reporting. Could you compile the wtlay again with debug traces, instructions are:
`cd /usr/local/bioinfo/src/smartdenovo/smartdenovo/`
`rm wtlay`
`make DEBUG=1 wtlay`
`gdb wtlay`
`gdb> run -i All7.fa.gz and your other parameters`
When crash, please type `backtrace`
BTW, what's your fill command when calling wtlay?

**Comment by chklopp** [comment]
gdb /usr/local/bioinfo/src/smartdenovo/smartdenovo/wtlay
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-75.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/bioinfo/src/smartdenovo/smartdenovo/wtlay...done.
(gdb) run -i All7.fa.gz -b All7.dmo.obt -j All7.dmo.ovl -fo All7.dmo.lay -w 300 -s 200 -m 0.1 -r 0.95 -c 1
Starting program: /usr/local/bioinfo/src/smartdenovo/smartdenovo/wtlay -i All7.fa.gz -b All7.dmo.obt -j All7.dmo.ovl -fo All7.dmo.lay -w 300 -s 200 -m 0.1 -r 0.95 -c 1
[Thread debugging using libthread_db enabled]
Detaching after fork from child process 90604.
[Mon Oct 30 15:01:50 2017] loading reads
[Mon Oct 30 15:06:31 2017] Done, 1023177 reads
[Mon Oct 30 15:06:31 2017] loading reads obt information
[Mon Oct 30 15:06:34 2017] Done
[Mon Oct 30 15:06:34 2017] loading alignments
loaded 51054474 overlaps
building edges
16795914 fine overlaps
[Mon Oct 30 15:11:25 2017] Done
[Mon Oct 30 15:11:25 2017] calculating edge coverage ...
[Mon Oct 30 15:12:58 2017] removed 1026 duplicate edges
[Mon Oct 30 15:12:58 2017] Done
[Mon Oct 30 15:14:20 2017] masked 733377 contained reads
[Mon Oct 30 15:14:21 2017] masked 25606 low coverage (<1) edges
[Mon Oct 30 15:14:24 2017] 'best_overlap' cut 6301202 non-best edges
11908 tips, 3797 bubbles, 46 chimera, 3900 non-bog, 25 recoveries
[Mon Oct 30 15:14:26 2017] repair 19630 bog elements
363 tips, 10 bubbles, 0 chimera, 97 non-bog, 3 recoveries
[Mon Oct 30 15:14:27 2017] repair 473 bog elements
18 tips, 1 bubbles, 0 chimera, 12 non-bog, 0 recoveries
[Mon Oct 30 15:14:28 2017] repair 31 bog elements
3 tips, 0 bubbles, 0 chimera, 0 non-bog, 0 recoveries
[Mon Oct 30 15:14:29 2017] repair 3 bog elements
0 tips, 0 bubbles, 0 chimera, 0 non-bog, 0 recoveries
[Mon Oct 30 15:14:31 2017] generated 18171 unitigs
[Mon Oct 30 15:14:31 2017] recovered 2594 edges inter unitigs

Program received signal SIGSEGV, Segmentation fault.
0x0000000000415211 in merge_bubble_core_best_overlap_strgraph (g=0x639190, hash=0x2fadc10, bts=0x7fffffffc440, node_id=153581, dir=0) at wtlay.c:1660
1660		e2 = edge_strgraph(g, e2->node_id, !e2->dir, e2->rev_idx);
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.5.x86_64

**Comment by ruanjue** [comment]
Please checkout b396f754644ddb3f703ae777fab9a14da786a66c
