### ISSUE TITLE
Error while trying to run smartdenovo

### ISSUE THREAD

**Issue by caonetto** [ruanjue/smartdenovo#11]
Hi, I am trying to run smartdenovo but I keep on getting this output 

`ubuntu@biolinux:/mnt/Federico/TD_1/Smartdenovo_assembly$ '/home/ubuntu/miniconda3/pkgs/smartdenovo-1.0.0-pl5.22.0_1/bin/smartdenovo.pl' /mnt/Federico/TD_1/basecalled.fasta
PREFIX=wtasm

EXE_PRE=/home/ubuntu/miniconda3/pkgs/smartdenovo-1.0.0-pl5.22.0_1/bin/wtpre
EXE_ZMO=/home/ubuntu/miniconda3/pkgs/smartdenovo-1.0.0-pl5.22.0_1/bin/wtzmo
EXE_OBT=/home/ubuntu/miniconda3/pkgs/smartdenovo-1.0.0-pl5.22.0_1/bin/wtobt
EXE_GBO=/home/ubuntu/miniconda3/pkgs/smartdenovo-1.0.0-pl5.22.0_1/bin/wtgbo
EXE_CLP=/home/ubuntu/miniconda3/pkgs/smartdenovo-1.0.0-pl5.22.0_1/bin/wtclp
EXE_LAY=/home/ubuntu/miniconda3/pkgs/smartdenovo-1.0.0-pl5.22.0_1/bin/wtlay
EXE_CNS=/home/ubuntu/miniconda3/pkgs/smartdenovo-1.0.0-pl5.22.0_1/bin/wtcns
N_THREADS=8

all:$(PREFIX).dmo.lay

$(PREFIX).fa.gz:
        $(EXE_PRE) -J 5000 /mnt/Federico/TD_1/basecalled.fasta | gzip -c -1 > $@

$(PREFIX).dmo.ovl:$(PREFIX).fa.gz
        $(EXE_ZMO) -t $(N_THREADS) -i $(PREFIX).fa.gz -fo $@ -k 16 -z 10 -Z 16 -U -1 -m 0.1 -A 1000

$(PREFIX).dmo.obt:$(PREFIX).fa.gz $(PREFIX).dmo.ovl
        $(EXE_CLP) -i $(PREFIX).dmo.ovl -fo $@ -d 3 -k 300 -m 0.1 -FT

$(PREFIX).dmo.lay:$(PREFIX).fa.gz $(PREFIX).dmo.obt $(PREFIX).dmo.ovl
        $(EXE_LAY) -i $(PREFIX).fa.gz -b $(PREFIX).dmo.obt -j $(PREFIX).dmo.ovl -fo $(PREFIX).dmo.lay -w 300 -s 200 -m 0.1 -r 0.95 -c 1
`

If I include the output > genome.mak   nothing happens, Any ideas?  Thanks

**Comment by ruanjue** [comment]
The scripts generated by smartdenovo,pl looks fine. Maybe you forgot to run make on it. 
`make -f genome.mak`
Or there should be error message from `make`.

**Comment by caonetto** [comment]
Thanks Ranjue, it worked at the end. One questions, is it possible to run smartdenovo on fastq error corrected reads?

**Comment by ruanjue** [comment]
Yes, someone did it successfully. However, smartdenovo solve the problem of long noisy reads, not designed to assemble corrected long reads. If you got 'looks-better' contigs, please be careful to check the large misassewmblies, inside parameters to untangle graph may be not suit for corrected reads (I haven't tested it nor thought about it).

**Comment by caonetto** [comment]
So you would recommend doing the assembly with the raw reads and then doing a polishing (nanopolish)?

Thanks

**Comment by ruanjue** [comment]
Yes, I prefer to assemble raw reads and then polish contigs. In my view, raw reads correction doesn't consider global information of genome.
