### ISSUE TITLE
Generate consensus fasta file with Smartdenovo

### ISSUE THREAD

**Issue by a-velt** [ruanjue/smartdenovo#12]
Dear developpers,

First, thank you for your great tool, smartdenovo.

I launched this tools, which is very fast, awesome.

In your documentation, you said to run the following commands :

```
/path/to/smartdenovo/smartdenovo.pl -p prefix reads.fa > prefix.mak
make -f prefix.mak
```

That’s what I did but I don’t get a « .cns » file and I don’t have any lines that generate it in my make file.

My make file : 

> PREFIX=GW_smartdenovo
> 
> EXE_PRE=/path/to/smartdenovo/wtpre
> EXE_ZMO=/path/to/smartdenovo/wtzmo
> EXE_OBT=/path/to/smartdenovo/wtobt
> EXE_GBO=/path/to/smartdenovo/wtgbo
> EXE_CLP=/path/to/smartdenovo/wtclp
> EXE_LAY=/path/to/smartdenovo/wtlay
> EXE_CNS=/path/to/smartdenovo/wtcns
> N_THREADS=10
> 
> all:$(PREFIX).dmo.lay
> 
> $(PREFIX).fa.gz:
>         $(EXE_PRE) -J 5000 raw_reads.GW.fasta | gzip -c -1 > $@
> 
> $(PREFIX).dmo.ovl:$(PREFIX).fa.gz
>         $(EXE_ZMO) -t $(N_THREADS) -i $(PREFIX).fa.gz -fo $@ -k 16 -z 10 -Z 16 -U -1 -m 0.1 -A 1000
> 
> $(PREFIX).dmo.obt:$(PREFIX).fa.gz $(PREFIX).dmo.ovl
>         $(EXE_CLP) -i $(PREFIX).dmo.ovl -fo $@ -d 3 -k 300 -m 0.1 -FT
> 
> $(PREFIX).dmo.lay:$(PREFIX).fa.gz $(PREFIX).dmo.obt $(PREFIX).dmo.ovl
>         $(EXE_LAY) -i $(PREFIX).fa.gz -b $(PREFIX).dmo.obt -j $(PREFIX).dmo.ovl -fo $(PREFIX).dmo.lay -w 300 -s 200 -m 0.1 -r 0.95 -c 1
> 

My outputs : 

> GW_smartdenovo.dmo.lay
> GW_smartdenovo.dmo.lay.1.dot
> GW_smartdenovo.dmo.lay.2.dot
> GW_smartdenovo.dmo.lay.3.dot
> GW_smartdenovo.dmo.lay.4.dot
> GW_smartdenovo.dmo.lay.5.dot
> GW_smartdenovo.dmo.lay.contained_reads
> GW_smartdenovo.dmo.lay.dup
> GW_smartdenovo.dmo.lay.lnk
> GW_smartdenovo.dmo.lay.utg
> GW_smartdenovo.dmo.lay.utg.dup
> GW_smartdenovo.dmo.obt
> GW_smartdenovo.dmo.ovl
> GW_smartdenovo.dmo.ovl.contained
> GW_smartdenovo.fa.gz
> GW_smartdenovo.mak

Is it the file « .dmo.lay.utg » that is the final assembly ? Was there a polishing step ? Knowing that I have « quiver » available on the server on which I launched smartdenovo.

Thank you for your response.
Best,
Amandine

**Comment by ruanjue** [comment]
/path/to/smartdenovo/smartdenovo.pl -p prefix reads.fa -c 1 > prefix.mak
-c 1 will generate the consensus command line

**Comment by a-velt** [comment]
Dear Jue Ruan,

I launch the command with the -c 1 option and I have the following outputs : 

GW_smartdenovo.dmo.lay.utg.dup
GW_smartdenovo.dmo.lay.lnk
GW_smartdenovo.dmo.lay.utg
GW_smartdenovo.dmo.lay.dup
GW_smartdenovo.dmo.lay
GW_smartdenovo.dmo.lay.5.dot
GW_smartdenovo.dmo.lay.4.dot
GW_smartdenovo.dmo.lay.3.dot
GW_smartdenovo.dmo.lay.2.dot
GW_smartdenovo.dmo.lay.contained_reads
GW_smartdenovo.dmo.lay.1.dot
GW_smartdenovo.dmo.obt
GW_smartdenovo.dmo.ovl
GW_smartdenovo.dmo.ovl.contained
 GW_smartdenovo.fa.gz
GW_smartdenovo.mak

But no consensus file seems to be here ... Is it normal ?

Best,
Amandine

**Comment by ruanjue** [comment]
I am not sure why smartdenovo.pl -c 1 didn't work. Please run the consensus by yourself.

wtcns -t 10 GW_smartdenovo.dmo.lay > GW_smartdenovo.dmo.cns.fa
