### ISSUE TITLE
No .cns file

### ISSUE THREAD

**Issue by HTaekOppa** [ruanjue/smartdenovo#13]
Dear SMARTdenovo,

Hope this email finds you well. I assume “smartdenovo.pl” includes all these programs: wtzmo, wtgbo, wtclp, ctcns, and wtmsa.

After running this script 
/smartdenovo/smartdenovo.pl -p prefix reads.fa > prefix.mak
make -f prefix.mak

It was supposed to generate “prefix.cns” but I could not find it. The generated files are .lay, .lay.dup, .lay.utg, .lay.utg.dup, and dmo.ovl.

Did I miss something? 

Looking forward to your reply!

Best regards,

Taek

**Comment by ruanjue** [comment]
Please have a look at #12 . If the `smartdenovo.pl -c 1` doesn't work for you too, please give me a message.
