### ISSUE TITLE
output fastq from wtcns

### ISSUE THREAD

**Issue by njaupan** [ruanjue/smartdenovo#20]
Dear ruanjue,

May i ask can i get fastq file from wtcns? I need fastq file for downstream analysis such as reads alignment. From now, i can only obtain fasta from wtcns.

Best,
panpan

**Comment by ruanjue** [comment]
wtcns doesn't evaluate the base quality of cosnensus sequences, so no quality available. One way to generate fastq is set all base quanlity to 30.
