### ISSUE TITLE
Kmer selection

### ISSUE THREAD

**Issue by njaupan** [ruanjue/smartdenovo#21]
Dear Ruanjue,

If I understand correctly, smartdenovo works very different from DBG assemblers, is kind of OLC assembler. So i am not sure if kmer selection should be done based on Jelleyfish or Kmergenie. Therefore, how to select kmer size for smartdenovo?

Sincrely,
panpan

**Comment by ruanjue** [comment]
K-mer is used in SMARTdenovo for reads aligning. The default setting is ok in most case. For more details, please have a look at https://github.com/ruanjue/smartdenovo/blob/master/README-tools.md .
