### ISSUE TITLE
Compiation failed on "undefined reference to `cut_biedge_strgraph2'"

### ISSUE THREAD

**Issue by yoann-dufresne** [ruanjue/smartdenovo#22]
Hi,

I just tried to download and compile smartdenovo using your command lines:  
```bash
git clone https://github.com/ruanjue/smartdenovo.git  
cd smartdenovo  
make  
```
but the compilation endend on:  
```bash
/tmp/ccBHOwYi.o: In function `merge_bubbles_strgraph':
wtlay.c:(.text+0x984d): undefined reference to `cut_biedge_strgraph2'
wtlay.c:(.text+0x9861): undefined reference to `cut_biedge_strgraph2'
wtlay.c:(.text+0x992d): undefined reference to `cut_biedge_strgraph2'
wtlay.c:(.text+0x994a): undefined reference to `cut_biedge_strgraph2'
collect2: error: ld returned 1 exit status
Makefile:48: recipe for target 'wtlay' failed
make: *** [wtlay] Error 1
make: *** Waiting for unfinished jobs....
```

Do you have any idea of what could resolve this issue ?  
(I am running on an ubuntu 18.04 up to date)

Yo

**Comment by yoann-dufresne** [comment]
I did not specify but I am running on an ubuntu 18.04 up to date

**Comment by yoann-dufresne** [comment]
It works with this modification.

But I don't understand why this code doesn't work with the inline keyword...

**Comment by ruanjue** [comment]
I have no idea, maybe compilers diffs.

**Comment by yoann-dufresne** [comment]
I just found that:
https://stackoverflow.com/questions/19068705/undefined-reference-when-calling-inline-function

Do you have a significant time improvement with this inlined function ?  
Maybe you should consider to change the inline to static for all users ?

Thanks for the solution
Yo

**Comment by ruanjue** [comment]
Thanks Yo,
I used `static inline`, but user reported floods of compile errors. Then I changed to `inline`. 

Best,
Jue

**Comment by WhaleKlng** [comment]
I tried, and I did add static！
