### ISSUE TITLE
SMARTdenovo failure

### ISSUE THREAD

**Issue by gabster** [ruanjue/smartdenovo#23]
Hi,
I run SMARTdenovo on some canu corrected reads. In the end it finished with this error message:
CA690_canu.mak:27: recipe for target 'CA690_canu.dmo.cns' failed
make: *** [CA690_canu.dmo.cns] Error 1

What can I do?
Cheers Gabi

**Comment by gabster** [comment]
Yes, it does exist

**Comment by ruanjue** [comment]
Can you have a look at CA690_canu.dmo.cns.log, and give me more message.

**Comment by gabster** [comment]
Dear Jue,
I am attaching the log file.
Thanks Gabi

Gabriele Margos
German National Reference Centre for Borrelia
Bavarian Health and Food Safety Authority
Veterinärstrasse 2
85764 Oberschleißheim
Tel. 09131/68085883
email:
gmargos1@gmail.com<mailto:gmargos1@gmail.com>
gabriele.margos@lgl.bayern.de<mailto:gabriele.margos@lgl.bayern.de>


Von: Jue Ruan [mailto:notifications@github.com]
Gesendet: Donnerstag, 30. August 2018 13:28
An: ruanjue/smartdenovo
Cc: Margos, Gabriele, Dr. (LGL); Author
Betreff: Re: [ruanjue/smartdenovo] SMARTdenovo failure (#23)


Can you have a look at CA690_canu.dmo.cns.log, and give me more message.

**Comment by ruanjue** [comment]
I cannot find the log file.

**Comment by gabster** [comment]
Hi, it was attached to the mail. I am copying it here:


[Tue Aug 28 18:25:09 2018]"utg4 length=182973 nodes=239" init
[Tue Aug 28 18:25:09 2018]"utg4 length=182973 nodes=239" generate backbone length=183036
[Tue Aug 28 18:25:11 2018]"utg4 length=182973 nodes=239" align aln_score=3130893
[Tue Aug 28 18:25:11 2018]"utg4 length=182973 nodes=239" merge nodes
[Tue Aug 28 18:25:11 2018]"utg4 length=182973 nodes=239" iter1 length=187454 aln_score=3130893 cns_score=813878.312500
[Tue Aug 28 18:25:12 2018]"utg4 length=182973 nodes=239" align aln_score=3302350
[Tue Aug 28 18:25:12 2018]"utg4 length=182973 nodes=239" merge nodes
[Tue Aug 28 18:25:12 2018]"utg4 length=182973 nodes=239" iter2 length=187054 aln_score=3302350 cns_score=806780.625000
[Tue Aug 28 18:25:14 2018]"utg4 length=182973 nodes=239" align aln_score=3307951
[Tue Aug 28 18:25:14 2018]"utg4 length=182973 nodes=239" merge nodes
[Tue Aug 28 18:25:14 2018]"utg4 length=182973 nodes=239" iter3 length=187167 aln_score=3307951 cns_score=807200.500000
[Tue Aug 28 18:25:15 2018]"utg4 length=182973 nodes=239" align aln_score=3308283
[Tue Aug 28 18:25:15 2018]"utg4 length=182973 nodes=239" merge nodes
[Tue Aug 28 18:25:15 2018]"utg4 length=182973 nodes=239" iter4 length=187059 aln_score=3308283 cns_score=806998.125000
[Tue Aug 28 18:25:16 2018]"utg4 length=182973 nodes=239" align aln_score=3308078
[Tue Aug 28 18:25:16 2018]"utg4 length=182973 nodes=239" merge nodes
[Tue Aug 28 18:25:16 2018]"utg4 length=182973 nodes=239" iter5 length=187167 aln_score=3308078 cns_score=807204.312500
[Tue Aug 28 18:25:18 2018]"utg4 length=182973 nodes=239" align aln_score=3308268
[Tue Aug 28 18:25:18 2018]"utg4 length=182973 nodes=239" merge nodes
[Tue Aug 28 18:25:18 2018]"utg4 length=182973 nodes=239" iter6 length=187053 aln_score=3308268 cns_score=806977.562500
[Tue Aug 28 18:25:18 2018]"utg5 length=889920 nodes=10067" init
[Tue Aug 28 18:25:18 2018]"utg5 length=889920 nodes=10067" generate backbone length=889991
-- Out of memory, try to allocate 3489660915 bytes, old size 1610612730, old addr 0x7f66f37e4010 in encap_list -- list.h:65 --


Gabriele Margos
German National Reference Centre for Borrelia
Bavarian Health and Food Safety Authority
Veterinärstrasse 2
85764 Oberschleißheim
Tel. 09131/68085883
email:
gmargos1@gmail.com<mailto:gmargos1@gmail.com>
gabriele.margos@lgl.bayern.de<mailto:gabriele.margos@lgl.bayern.de>


Von: Margos, Gabriele, Dr. (LGL)
Gesendet: Donnerstag, 30. August 2018 13:53
An: 'ruanjue/smartdenovo'; ruanjue/smartdenovo
Cc: Author
Betreff: AW: [ruanjue/smartdenovo] SMARTdenovo failure (#23)

Dear Jue,
I am attaching the log file.
Thanks Gabi

Gabriele Margos
German National Reference Centre for Borrelia
Bavarian Health and Food Safety Authority
Veterinärstrasse 2
85764 Oberschleißheim
Tel. 09131/68085883
email:
gmargos1@gmail.com<mailto:gmargos1@gmail.com>
gabriele.margos@lgl.bayern.de<mailto:gabriele.margos@lgl.bayern.de>


Von: Jue Ruan [mailto:notifications@github.com]
Gesendet: Donnerstag, 30. August 2018 13:28
An: ruanjue/smartdenovo
Cc: Margos, Gabriele, Dr. (LGL); Author
Betreff: Re: [ruanjue/smartdenovo] SMARTdenovo failure (#23)


Can you have a look at CA690_canu.dmo.cns.log, and give me more message.

**Comment by ruanjue** [comment]
> -- Out of memory, try to allocate 3489660915 bytes, old size 1610612730, old addr 0x7f66f37e4010 in encap_list -- list.h:65 --
Out of memory! Please find a PC with larger RAM.

**Comment by gabster** [comment]
Hi Jue,
I am sorry, I did not see that. I had a previous run on same data without canu correction and that worked.
Thanks for your support,
Gabi

Gabriele Margos
German National Reference Centre for Borrelia
Bavarian Health and Food Safety Authority
Veterinärstrasse 2
85764 Oberschleißheim
Tel. 09131/68085883
email:
gmargos1@gmail.com<mailto:gmargos1@gmail.com>
gabriele.margos@lgl.bayern.de<mailto:gabriele.margos@lgl.bayern.de>


Von: Jue Ruan [mailto:notifications@github.com]
Gesendet: Donnerstag, 30. August 2018 14:17
An: ruanjue/smartdenovo
Cc: Margos, Gabriele, Dr. (LGL); Author
Betreff: Re: [ruanjue/smartdenovo] SMARTdenovo failure (#23)


-- Out of memory, try to allocate 3489660915 bytes, old size 1610612730, old addr 0x7f66f37e4010 in encap_list -- list.h:65 --
Out of memory! Please find a PC with larger RAM.
