### ISSUE TITLE
wtzmo中的参数

### ISSUE THREAD

**Issue by AmicPair** [ruanjue/smartdenovo#25]
hello，ruanjue！
wtzmo中的参数 -k： 为什么设置5-32的范围，大于32或者放开限制会怎样？

**Comment by ruanjue** [comment]
-k 32 is large enough, and should never be used in practice. Also, -k 32 is limited by data structure uint64_t. 

BTW, I think minimap2 should work better than wtzmo, you can have a try if have interests.

Jue
