### ISSUE TITLE
How does a SMARTdenovo output file look like

### ISSUE THREAD

**Issue by biowackysci** [ruanjue/smartdenovo#26]
Hello All, 
I am trying to do a smartdenovo assembly on my PacBio and Nanopore MinION and PromethION generated data. I got upto the .cns files and then I am not sure what is meant to happen from there. I was hoping a summary file with the number of contigs and the N50 all that would be generated but could not find any of it. Can you suggest how do i look for it, please? 
I use the script 
/group/pasture/Saila/Smartdenovo/smartdenovo-master/smartdenovo.pl -p saila_smartdenovo -c 1 /group/pasture/Saila/Smartdenovo/all_fastq_files/all_fastq_files_smartdenovo.fastq > saila_smartdenovo.mak

make -f saila_smartdenovo.mak

The type of files I got so far are 
.cns.log
.cns
.lay.utg.dup
.utg
.lnk
.dup
.lay
.lay.1/2/3/4/5.dot
lay.contained_reads
.dmo.obt
.ovl.contained
.ovl

And no summary or fasta files. So I am a bit confused about it.

Thanks 
Saila

**Comment by ruanjue** [comment]
Please have a look at the .cns file, the contig sequences.

BTW, I will maintain more on wtdbg2 than SMARTdenovo, have a try.
