### ISSUE TITLE
separating similar chromosome parts in corrected read assemblies

### ISSUE THREAD

**Issue by chklopp** [ruanjue/smartdenovo#27]
We are assembling a large genome (close to 2 Gb). We have corrected the reads with canu and assembled them with smartdenovo. The assembly size is 16% lower than expected. Some chromosomes share large sub-sequences which are assembled only once and collected twice the average read depth when we realign the reads on the assembly. We think that these parts have not different enough sequences to be separated by smartdenovo with standard parameters. 
Have you already seen this? 
Which parameter(s) should we change to try to separate both parts?

**Comment by ruanjue** [comment]
`-m` in `wtzmo` may help. Please note that I am maintaining wtdbg2 instead of smartdenovo, please try wtdbg2.
