### ISSUE TITLE
wtpoa-cns bam correction stage segmentation fault

### ISSUE THREAD

**Issue by yuwwu** [ruanjue/smartdenovo#28]
Dear colleague,
Greetings. I am trying your wtdbg2 v2.2 on my data. I have about two million long reads, and wtdbg2/wtpoa-cns successfully assemble them into several thousands of contigs. I however encountered some difficulties trying to correct the assembly using bam file generated using minimap2. The command that I issued is exactly the same as specified in the wiki, which is

samtools view profile.ctg.lay.map.srt | ./wtpoa-cns -t 16 -d profile.ctg.lay.fa -i - -fo profile.ctg.lay.2nd.fa -v

I added "-v" for more verbose output and see the program stops here

(omitted)
JOINT	222259	qe = 2005 -> 2005	te = 497 -> 497	[ 2005, 2015]	[  499,  496,1,2,0]
Segmentation fault (core dumped)

Please kindly let me know if you have any suggestions. Thank you.

**Comment by ruanjue** [comment]
I will polish the short reads consensus codes.

BTW, please open issue under wtdbg2. SMARTdenovo is infrequently maintained now.
