### ISSUE TITLE
It would be good to have an actual release of this.

### ISSUE THREAD

**Issue by akesandgren** [ruanjue/smartdenovo#30]
Making a release with an actual version number makes it easier to know exactly what has been installed on a system. Especially HPC sysadmins like versioned software.

**Comment by ruanjue** [comment]
SMARTdenovo will stay as it is now.

**Comment by alanorth** [comment]
@akesandgren I agree. In cases like this I usually just install the software on our cluster with a version like `git-ed07d988`. :man_shrugging:
