### ISSUE TITLE
dmo.lay.

### ISSUE THREAD

**Issue by Lutri22** [ruanjue/smartdenovo#31]
Hi, 

I am trying to use smartdenovo to assemble an invertebrate genome (700Mb genome size) used by 30X coverage from nanopore sequencing. I know that the final output is the .cns file, however, the N50 of the cns file is ~100Kb while we got 500Kb in the case of the dmo.lay file (with 5.4G total assembly size). So my questions are the following: Is this decrease is normal during the consensus step or not? Is there any way to use the dmo.lay file and try to get rid of the redundancy somehow?

Many thanks 

Szabolcs

**Comment by ruanjue** [comment]
The dmo.lay file contains no sequences, did you stat the contig headers? 

Also please use wtdbg2 to instead SMARtdenovo.
