### ISSUE TITLE
How to run wtzmo parallelly

### ISSUE THREAD

**Issue by Jolvii85** [ruanjue/smartdenovo#33]
Hi Ruanjue

I am assembling a big genome (>20Gbp), I would like to run wtzmo parallelly, i.e. 10 parts, can you give an example about how to set parameters?  And if I run wtzmo parallelly, will the memory usage reduce?

Thank you very much.

**Comment by ruanjue** [comment]
```sh
wtzmo -P 10 -p 0 ...
wtzmo -P 10 -p 1 ...
...
wtzmo -P 10 -p 9
```
If run parallely, each job will take the same memory with standalone.

As you are assembling 20G genome, please have a try with wtdbg2 (v2.3), which is designed to handle huge genomes.

Jue

**Comment by Jolvii85** [comment]
Hi,

If I run wtzmo parallelly, should I give the output different name (I guess yes)? If yes,  After combining all the results to one file, do I need sort the file?  

Thank you!
I am running wtdbg2 too, it is a good assembler also.

**Comment by ruanjue** [comment]
It is ok, spliting reads will change the k-mer table, and result in some difference.
