### ISSUE TITLE
polishing Smartdenovo assembly

### ISSUE THREAD

**Issue by biowackysci** [ruanjue/smartdenovo#37]
Hello,
I have a couple of questions. 
1) I was thinking of using Racon to polish the smartdenovo assembly. Racon suggests to use these reads:
racon [options ...] <sequences> <overlaps> <target sequences>

    <sequences>
        input file in FASTA/FASTQ format (can be compressed with gzip)
        containing sequences used for correction
    <overlaps>
        input file in MHAP/PAF/SAM format (can be compressed with gzip)
        containing overlaps between sequences and target sequences
    <target sequences>
        input file in FASTA/FASTQ format (can be compressed with gzip)
        containing sequences which will be corrected
for the first sequences, I can give illumina reads as the input , I am not sure what would be the best input for the second sequnces as smartdenovo does not make any mhap files like other assemblers like Canu and for the third sequences I will input the .cns file generated by smartdenovo assembly.

Can you please help me out what needs to go in the input files for the overlaps?
2) is there a better polishing tool other than Racon for Smartdenovo assembly? Note : I have used long reads from both PacBio and Nanopore for my assembly 

Thanks heaps in advance 
S

**Comment by ruanjue** [comment]
I am not sure how to run Racon, but from your description, PAF and SAM file can be generated by minimap2. I used to polish the contigs with Quiver and pilon.

Best,
Jue
