### ISSUE TITLE
error while running smartdenovo

### ISSUE THREAD

**Issue by tanu121093** [ruanjue/smartdenovo#38]
i am getting the following error when i run the software, the following commands were used to run
 /home/pbp/smartdenovo/smartdenovo.pl -p haemo3_smartdenovo -c 1 /home/pbp/Documents/run7/run7_filtered/PSHaemo3.fastq > /home/pbp/Documents/run7/run7_filtered/haemo3_smartdenovo.mak make -f haemo3_smartdenovo.mak
 make -f pbp_smartdenovo.mak                                                              
make: pbp_smartdenovo.mak: No such file or directory
make: *** No rule to make target `pbp_smartdenovo.mak'.  Stop.
help to resolve this issue

**Comment by ruanjue** [comment]
Please confirm this commands
```sh
/home/pbp/smartdenovo/smartdenovo.pl -p haemo3_smartdenovo -c 1 /home/pbp/Documents/run7/run7_filtered/PSHaemo3.fastq > /home/pbp/Documents/run7/run7_filtered/haemo3_smartdenovo.mak
make -f haemo3_smartdenovo.mak
make -f pbp_smartdenovo.mak
```
OR
```sh
/home/pbp/smartdenovo/smartdenovo.pl -p haemo3_smartdenovo -c 1 /home/pbp/Documents/run7/run7_filtered/PSHaemo3.fastq > /home/pbp/Documents/run7/run7_filtered/haemo3_smartdenovo.mak make -f haemo3_smartdenovo.mak
make -f pbp_smartdenovo.mak
```

**Comment by tanu121093** [comment]
the command used were

/home/pbp/smartdenovo/smartdenovo.pl -p haemo3_smartdenovo -c 1 /home/pbp/Documents/run7/run7_filtered/PSHaemo3.fastq >  /home/pbp/Documents/run7/run7_filtered/haemo3_smartdenovo.makmake -f haemo3_smartdenovo.mak

**Comment by ruanjue** [comment]
Please type your commands in the well format, also give me the error message.
