### ISSUE TITLE
the output file is null

### ISSUE THREAD

**Issue by wuxiaopei0509** [ruanjue/smartdenovo#39]
I run the smartdenovo.pl,but the output file is null ,and I don't know why,my command is as follows:
 /data/wuxiaopei/software/smartdenovo/smartdenovo/smartdenovo.pl –c 1 –p SMARTdenovo_longest_50X longest_50X.fasta > SMARTdenovo_longest_50X.mak
make -f SMARTdenovo_longest_50X.mak

the output is :
![图片](https://user-images.githubusercontent.com/52643750/63691367-959c7900-c841-11e9-9ad4-20b73bbce092.png)

**Comment by ruanjue** [comment]
Was there any error message?
