### ISSUE TITLE
Assembly of the mitochondrion

### ISSUE THREAD

**Issue by bistace** [ruanjue/smartdenovo#4]
Hi,
I used SMARTdenovo on  a yeast strain to assemble it with Nanopore reads. I obtained a very good continuity but in the output `*.dmo.cns`, I can only find a part of the mitochondrion. 

If I align the `*.utg.dup` against the reference genome, I can see that the mitochondrion is present in its entirety. I think that maybe SMARTdenovo is rejecting parts of the mitochondrion due to a very high coverage, since it's present in unitigs but not in contigs. 

I tried to decrease the coverage of reads given as input to SMARTdenovo but didn't obtain better results. 

Do you have any tips concerning the parameters I could use to get the mitochondrion assembled in the consensus file ?

**Comment by ruanjue** [comment]
In fact, SMARTdenovo doesn't filter assemblies of high coverage. utgs in `*.utg.dup` are somehow similiar with utgs in `*.utg`. `wtlay -q 0.4` says if utgA can be aligned against a longer utgB with at least 40% of its length, utgA should be discarded and written to `*.utg.dup`. 

So, I suggest to increase the parameter of `wtlay -q`. Also, please align the MT utgs from `*.utg.dup` against `*.utg` manually, and have a look at the sequence similarity.
