### ISSUE TITLE
why is wtgbo skipped when using dmo overlapper in smartdenovo.pl?

### ISSUE THREAD

**Issue by zhangrengang** [ruanjue/smartdenovo#40]
In `smartdenovo.pl`, `wtgbo` is used only in zmo overlapper mode. When using dmo overlapper in `wtzmo`, is it necessary to use `wtgbo` to rescue overlaps? I noticed that some overlaps between reads of high frequency, such as those derived from plastid, were missed.

**Comment by ruanjue** [comment]
`gbo` uses the same alignment algorithm (dynamic banded SW) with `zmo`. `dmo` uses k-mers synteny, so cannot cope with `gbo`.
