### ISSUE TITLE
About meaning of -c parameter

### ISSUE THREAD

**Issue by hungweichen0327** [ruanjue/smartdenovo#41]
Dear community,

The -c parameter is used to generate the consensus sequence. And I still not understand the meaning of value with -c parameter. For example:

```smartdenovo.pl -c 1 -J 1000 -k ${k} -p Crystal_c1s1_${k}mer ../Crystal_all_1kb.correctedReads.fasta > Crystal_v1.8_1kb_17mer.mak```

I don't know what's the difference if I changed -c 1 to -c 2, or -c 5. (Any more value? like -2?)
So far I have Nanopore corrected reads, and I want to use Smartdenovo to do assembly.

Thank you.

**Comment by ruanjue** [comment]
The same, -c bool_value, zero or non-zero.

**Comment by hungweichen0327** [comment]
Thank you for the fast reply. I got it!
