### ISSUE TITLE
Nanopore sequence commands 

### ISSUE THREAD

**Issue by bioramg** [ruanjue/smartdenovo#44]
Hi, 
I would like to assemble the nanopore plant mitochondrial genome sequence using SMARTdenonovo. But I could not find any commands to run this data. Could you please give commands for the same.

Thank you.

**Comment by ruanjue** [comment]
https://github.com/ruanjue/smartdenovo#getting-started
Try the standard commands.

**Comment by bioramg** [comment]
Thank you for quick reply.

/path/to/smartdenovo/smartdenovo.pl -p prefix -c 1 reads.fa > prefix.mak
make -f prefix.mak

what does mean by -p,  prefix.mak, and make -f prefix.mak?

**Comment by bioramg** [comment]
could you please give an example for nanopore assembly? Sorry to ask you. I am a very beginner.

**Comment by ruanjue** [comment]
```sh
/path/to/smartdenovo/smartdenovo.pl -p asm01 -c 1 ont_reads.fa > prefix.mak
make -f prefix.mak
```

**Comment by bioramg** [comment]
Thank you so much
