### ISSUE TITLE
Slurm exit code 2

### ISSUE THREAD

**Issue by dagi34** [ruanjue/smartdenovo#54]
Hi,
I am using Smartdenovo on a number of nodes. I installed it and carried out a run. However the run failed with exit code 2. I found that this means 'invalid usage of some shell built-in command. Examples of built-in commands include alias, echo, and printf'.
Does it have dependencies which I do not know about please?
### This is the .out file:
Running on nyquist
PREFIX=smartdenovo_ONT

EXE_PRE=smartdenovo/wtpre
EXE_ZMO=smartdenovo/wtzmo
EXE_OBT=smartdenovo/wtobt
EXE_GBO=smartdenovo/wtgbo
EXE_CLP=smartdenovo/wtclp
EXE_LAY=smartdenovo/wtlay
EXE_CNS=smartdenovo/wtcns
N_THREADS=24

all:$(PREFIX).dmo.cns

$(PREFIX).fa.gz:
	$(EXE_PRE) -J 5000 /opt/local/data/dagi1/ERR2173373.fastq | gzip -c -1 > $@

$(PREFIX).dmo.ovl:$(PREFIX).fa.gz
	$(EXE_ZMO) -t $(N_THREADS) -i $(PREFIX).fa.gz -fo $@ -k 16 -z 10 -Z 16 -U -1 -m 0.1 -A 1000

$(PREFIX).dmo.obt:$(PREFIX).fa.gz $(PREFIX).dmo.ovl
	$(EXE_CLP) -i $(PREFIX).dmo.ovl -fo $@ -d 3 -k 300 -m 0.1 -FT

$(PREFIX).dmo.lay:$(PREFIX).fa.gz $(PREFIX).dmo.obt $(PREFIX).dmo.ovl
	$(EXE_LAY) -i $(PREFIX).fa.gz -b $(PREFIX).dmo.obt -j $(PREFIX).dmo.ovl -fo $(PREFIX).dmo.lay -w 300 -s 200 -m 0.1 -r 0.95 -c 1

$(PREFIX).dmo.cns:$(PREFIX).dmo.lay
	$(EXE_CNS) -t $(N_THREADS) $< > $@ 2> $@.log

real	0m0.037s
user	0m0.025s
sys	0m0.005s
make: smartdenovo_ONT.mak: No such file or directory
make: *** No rule to make target 'smartdenovo_ONT.mak'.  Stop.

real	0m0.009s
user	0m0.006s
sys	0m0.001s

### and this is the text file to submit the job:
#!/bin/bash
#CPU and RAM resources
#SBATCH --partition=teaching_cpu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem-per-cpu=6G
#job parameters
#SBATCH --job-name=smartdenovo_ONT_arabidopsis
#email user
#SBATCH --mail-user=dorita.galea@um.edu.mt
#SBATCH --mail-type=all
#
echo Running on $(hostname) #name not required
source /opt/conda/etc/profile.d/conda.sh #activate conda env
conda activate dorita_env1
cd /opt/local/data/dagi1/ #path to data file
time smartdenovo/smartdenovo.pl -p smartdenovo_ONT -c 1 -t 24 /opt/local/data/dagi1/ERR2173373.fastq smartdenovo_ONT.mak
time make -f smartdenovo_ONT.mak

**Comment by ruanjue** [comment]
Please check this code
```sh
time smartdenovo/smartdenovo.pl -p smartdenovo_ONT -c 1 -t 24 /opt/local/data/dagi1/ERR2173373.fastq smartdenovo_ONT.mak
```
Maybe you missed a `>`

**Comment by dagi34** [comment]
Thanks.
Regards

**Comment by dagi34** [comment]
Thanks
