### ISSUE TITLE
The meaning of each output file

### ISSUE THREAD

**Issue by nottwy** [ruanjue/smartdenovo#8]
I'm interested in your tool after watching the report of Bjorn Usadel at 2017 London Calling.
I'm assembling an animal genome which is repeat-rich. I haven't got good assembly yet and want to test your tool. After running your tool following the steps you write in your github homepage, I got following files and don't know the meaning of some of files. Also I didn't see .cns file.

The following is the files generated.

wtasm.dmo.lay
wtasm.dmo.lay.dup
wtasm.dmo.lay.lnk
wtasm.dmo.lay.utg
wtasm.dmo.lay.utg.dup
wtasm.dmo.lay.4.dot
wtasm.dmo.lay.5.dot
wtasm.dmo.lay.3.dot
wtasm.dmo.lay.2.dot
wtasm.dmo.lay.contained_reads
wtasm.dmo.lay.1.dot
wtasm.dmo.obt
wtasm.dmo.ovl
wtasm.dmo.ovl.contained
wtasm.fa.gz

1. what's the meaning of : 
wtasm.dmo.lay.dup
wtasm.dmo.lay.lnk
wtasm.dmo.lay.utg
wtasm.dmo.lay.utg.dup
2. how to generate .cns file.

Thanks!

**Comment by ruanjue** [comment]
Hi, 

I guess you forget to add -c in smartdenovo.pl. Now, you can make consensus sequences by `wtcns -t 64 < wtasm.dmo.lay > wtasm.dmo.lay.cns`. 

wtasm.dmo.lay is layout file of unitigs
wtasm.dmo.lay.dup is layout for unitigs which is too small, or too similar with other longer untigs
wtasm.dmo.lay.utg is raw sequences for unitigs
wtasm.dmo.lay.utg.dup see wtasm.dmo.lay.dup
wtasm.dmo.lay.lnk is used for further untangling repeats, there are links of unitigs in assembly graph, but no program will read it

BTW, have a try of https://github.com/ruanjue/wtdbg-1.2.8, which is more friendly to run.

Jue

**Comment by nottwy** [comment]
Thanks for your reply! And I still have some problems.
1. is .utg file your final output of the assembly? I know the .cns file is the result after consensus. But the N50 of theses two files should be almost the same, isn't it?
2. In my case, I use the trim reads from canu as the input of SMARTdenovo but didn't get better result than canu. On the contrary, the result is much worse than the canu assembly result. So what's the correct operation of canu2SMARTdenovo? Should I adjust some parameters?
3. Is there any manuscript which introduces your tool?
Wait for your reply!

**Comment by ruanjue** [comment]
1, contigs size will be smaller after consensus, because of insertion > deletion in raw seuqneces
2, I am not familiar with canu2SMARTdenovo. I guess the wtobt is useless for the corrected reads, wtgbo is also useless, because GBO aims to rescue alignments of high error rate sequences. wtdmo and wtlay will be ok. Nevertheless, I havn't try it.
3, I have no plan to publish SMARTdenovo, because I have switched to WTDBG for more than two years.

Hope it helps.

**Comment by quokkamole** [comment]
What does the *.fa.gz file in the output contain?

Thanks
